config/routes.rb
Craigslist::Application.routes.draw do
  resources :posts

  resources :cities

  resources :brands

  match '/brands/getCaptcha' => 'brands#getCaptcha'
  match '/brands/getBalance' => 'brands#getBalance'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :posts
  attr_accessible :name, :discount, :value, :image_url, :description
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name, :url, :active
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :brand
  attr_accessible :brand_id, :title, :price, :value, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.find(:all, :conditions => "image_url is NOT NULL", :order => "value DESC")
    number_to_send_to = "4252838252"

    twilio_sid = "ACf08eef96de0705fe22b50e68d89dfd8b"
    twilio_token = "f20e09cc73536fad72b284c0fd506de5"
    twilio_phone_number = "2532371526"

    @twilio_client = Twilio::REST::Client.new(twilio_sid, twilio_token)
=begin
    @twilio_client.account.sms.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number_to_send_to,
      :body => "This is an message. It gets sent to #{number_to_send_to}"
    )
=end
  end

  def getCaptcha
    @rid  = params

    uri = URI.parse("https://www.plasticjungle.com/balance-check/getCaptchaForBrandProduct")
    https = Net::HTTP.new(uri.host,uri.port)
    https.use_ssl = true
    req = Net::HTTP::Post.new(uri.path)
    req.set_form_data({'brandProductId' => @rid['brandProductId']})
    start_time = Time.now
    begin
      res = https.request(req)
    rescue Timeout::Error
    end
    json = res.body
    respond_to do |format|
      format.js{
        render :json => json.to_json
      }
    end
  end

  def getBalance
    @rid  = params

    uri = URI.parse("https://www.plasticjungle.com/checkBalanceForSeller")
    https = Net::HTTP.new(uri.host,uri.port)
    https.use_ssl = true
    req = Net::HTTP::Post.new(uri.path)
    if @rid.has_key?(:captchaId) then
      req.set_form_data(
          {
            'productId' => @rid['brandProductId'],
            'cardNumber' => @rid['cardNumber'],
            'pin' => @rid['pin'],
            'captchaId' => @rid['captchaId'],
            'captchaInput' => @rid['captchaInput']
          })
    else
      req.set_form_data(
          {
            'productId' => @rid['brandProductId'],
            'cardNumber' => @rid['cardNumber'],
            'pin' => @rid['pin']
          })
    end
    start_time = Time.now
    begin
      res = https.request(req)
    rescue Timeout::Error
    end
    json = res.body
    respond_to do |format|
      format.js{
        render :json => json.to_json
      }
    end
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(params[:brand])
    if @brand.save
      redirect_to @brand, :notice => "Successfully created brand."
    else
      render :action => 'new'
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update_attributes(params[:brand])
      redirect_to @brand, :notice  => "Successfully updated brand."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy
    name = @brand['name']
    redirect_to brands_url, :notice => "Successfully destroyed #{name}."
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(params[:city])
    if @city.save
      redirect_to @city, :notice => "Successfully created city."
    else
      render :action => 'new'
    end
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    if @city.update_attributes(params[:city])
      redirect_to @city, :notice  => "Successfully updated city."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_to cities_url, :notice => "Successfully destroyed city."
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to @post, :notice => "Successfully created post."
    else
      render :action => 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to @post, :notice  => "Successfully updated post."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_url, :notice => "Successfully destroyed post."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/brands/_form.html.erb
<%= form_for @brand, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :discount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :discount, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :value, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :value, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                brands_path, :class => 'btn' %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/brands/index.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<div class = "row">
  <div class = "span10 offset1"/>
    <input id="searchInput" class="span8" type="text" placeholder="Start Typing"><br/>
    <!-- <%= link_to t('.new', :default => t("helpers.links.new")),
              new_brand_path,
              :class => 'btn btn-primary span8' %> -->
  </div>
  <table class="table table-striped table-condensed table-bordered table-hover" style="display:none">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:discount) %></th>
        <th><%= model_class.human_attribute_name(:value) %></th>
        <th><%= model_class.human_attribute_name(:image_url) %></th>
        <th><%= model_class.human_attribute_name(:description) %></th>
        <th><%= model_class.human_attribute_name(:updated_at) %></th>

        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody id="tbody">
      <% @brands.each_with_index do |brand,index| %>
        <tr class="data-link">
          <td><%= link_to index, brand_path(brand) %></td>
          <td><%= brand.name %></td>
          <td><%= brand.discount %></td>
          <td><p class="text-success"><%= brand.value %></p></td>
          <td><img src="<%=brand.image_url %>" class="img-rounded"</td>
          <td><%= brand.description %></td>
          <td><%=l brand.updated_at %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_brand_path(brand), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        brand_path(brand),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>


  <ul class="thumbnails span12">
    <% @brands.each_with_index do |brand,index| %>
    <li class="span2">
      <div class="thumbnail">
        <%= link_to(brand) do %>
          <img class="img-circle"src="<%=brand.image_url%>"/>
          <p class="text-info"><%=truncate(brand.name,:length => 15)%></p>
        <% end %>
      </div>
    </li>
    <%end%>
  </ul>
</div>

<!--
<ul class="ff-items span12">
  <% @brands.each_with_index do |brand,index| %>
  <li class="span2">
      <%= link_to(brand) do %>
        <span>
          <p id="brandName" style="display:none;"><%=brand.name%></p>
          <p class="text-success"><%= brand.value %></p>
          <p class="text-failure"><%= brand.retailer_id %></p>
        </span>    
        <img src="<%=brand.image_url%>"/>
        <p class="text-success"><%=brand.name%></p>

      <% end %>
  </li>
  <% end %>
</ul>
-->
<script>
String.prototype.score = function(abbreviation,offset) {
  offset = offset || 0 // TODO: I think this is unused... remove
 
  if(abbreviation.length == 0) return 0.9
  if(abbreviation.length > this.length) return 0.0

  for (var i = abbreviation.length; i > 0; i--) {
    var sub_abbreviation = abbreviation.substring(0,i)
    var index = this.indexOf(sub_abbreviation)


    if(index < 0) continue;
    if(index + abbreviation.length > this.length + offset) continue;

    var next_string       = this.substring(index+sub_abbreviation.length)
    var next_abbreviation = null

    if(i >= abbreviation.length)
      next_abbreviation = ''
    else
      next_abbreviation = abbreviation.substring(i)
 
    var remaining_score   = next_string.score(next_abbreviation,offset+index)
 
    if (remaining_score > 0) {
      var score = this.length-next_string.length;

      if(index != 0) {
        var j = 0;

        var c = this.charCodeAt(index-1)
        if(c==32 || c == 9) {
          for(var j=(index-2); j >= 0; j--) {
            c = this.charCodeAt(j)
            score -= ((c == 32 || c == 9) ? 1 : 0.15)
          }

          // XXX maybe not port this heuristic
          // 
          //          } else if ([[NSCharacterSet uppercaseLetterCharacterSet] characterIsMember:[self characterAtIndex:matchedRange.location]]) {
          //            for (j = matchedRange.location-1; j >= (int) searchRange.location; j--) {
          //              if ([[NSCharacterSet uppercaseLetterCharacterSet] characterIsMember:[self characterAtIndex:j]])
          //                score--;
          //              else
          //                score -= 0.15;
          //            }
        } else {
          score -= index
        }
      }
   
      score += remaining_score * next_string.length
      score /= this.length;
      return score
    }
  }
  return 0.0
}

jQuery.fn.liveUpdate = function(list){
  list = jQuery(list);

  if ( list.length ) {
    var rows = list.children('li'),//.children('a').children('span'),
      cache = rows.map(function(){
        return $(this).find('p')[0].innerHTML.toLowerCase();
      });
    this
      .keyup(filter).keyup()
      .parents('form').submit(function(){
        return false;
      });
  }
    
  return this;
    
  function filter(){
    var term = jQuery.trim( jQuery(this).val().toLowerCase() ), scores = [];
    if ( !term ) {
      rows.show();
    } else {
      rows.hide();
      cache.each(function(i){
        var score = this.score(term);
        if (score > .6) { 

          scores.push([score, i]); }
      });

      jQuery.each(scores.sort(function(a, b){return b[0] - a[0];}), function(){
        jQuery(rows[ this[1] ]).show();
        console.log(scores.length);
        if (scores.length == 1)
          console.log(rows[this[1]]);
          rows[this[1]].click();
      });
    }
  }
};

$(document).ready(function() {
  $('#searchInput').liveUpdate($('.thumbnails')).focus();
  
  $(document).keydown(function() { $('#searchInput').focus(); $('(#searchInput').select(); })
  /*  $.expr[':'].containsIgnoreCase = function(n,i,m){
          return jQuery(n).text().toUpperCase().indexOf(m[3].toUpperCase())>=0;
      };
      $("#searchInput").keyup(function(){
 //hide all the rows
          var data = $(this).val().split(" ");
            if (data[0] == ""){
              $(".ff-items").find("li").show();
              $("#tbody").find("tr").show();
            }else{
              $(".ff-items").find("li").hide();
              $("#tbody").find("tr").hide();
            }
           
 //split the current value of searchInput
          
 //create a jquery object of the rows
          var jo = $("#tbody").find("tr").find("td:nth-child(2)");
          var thumbs = $(".ff-items").find("span");
 //Recursively filter the jquery object to get results. 
          $.each(data, function(i, v){
              jo = jo.filter("*:containsIgnoreCase('"+v+"')");
              thumbs = thumbs.filter("*:containsIgnoreCase('"+v+"')");

          });
 //show the rows that match.
          jo.parent().show();
          thumbs.parent().parent().show();
 //Removes the placeholder text 
      }).focus(function(){
          this.value="";
          $(this).css({"color":"black"});
          $(this).unbind('focus');
      }).css({"color":"#C0C0C0"}); */
  });
  

</script>

app/views/brands/new.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/brands/show.html.erb
<%- model_class = Brand -%>
<!--
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @brand.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:discount) %>:</strong></dt>
  <dd><%= @brand.discount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:value) %>:</strong></dt>
  <dd><%= @brand.value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_url) %>:</strong></dt>
  <dd><%= @brand.image_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:retailer_id) %>:</strong></dt>
  <dd><%= @brand.retailer_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:captcha) %>:</strong></dt>
  <dd><%= @brand.captcha %></dd>
  
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              brands_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_brand_path(@brand), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              brand_path(@brand),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
-->
<div class="row">
  <div class="span8 offset2">
    <div id="holder">
    </div>
    <% if @brand.retailer_id != nil then %>
      <form id="idForm" class="form-horizontal">
        <div class="control-group">
          <label class="control-label" for="brandName">Brand</label>
          <div class="controls">
            <img class="img-rounded"src="<%=@brand.image_url%>"/>
          </div>
        </div>  
        <div class="control-group">
          <label class="control-label" for="cardNumber">Card Number</label>
          <div class="controls">
            <input type="text" id="cardNumber" class"span6" placeholder="Card Number">
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="pin">Pin</label>
          <div class="controls">
            <input type="text" id="pin" placeholder="Pin">
          </div>
        </div>
        <div class="control-group">
          <label class="control-label">Captcha Image</label>
          <div class="controls">
            <div class="span2" id="imgHolder"></div>
          </div>
        </div>
         <div id="captchaLine" class="control-group" style="display:none;">
          <label class="control-label" for="captcha">Captcha Text</label>
          <div class="controls">
            <input type="text" id="captchaText" placeholder="Captcha">
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <button id="submitButtonId" ype="submit" data-loading-text="Retreiving Balance" class="btn btn-large btn-block btn-primary">Get Balance</button>
          </div>
        </div>
      </form>
    <% end %>
  </div>
</div>
<script>



$('#submitButtonId').button();

var opts = {
  lines: 13, // The number of lines to draw
  length: 7, // The length of each line
  width: 4, // The line thickness
  radius: 10, // The radius of the inner circle
  corners: 1, // Corner roundness (0..1)
  rotate: 0, // The rotation offset
  color: '#000', // #rgb or #rrggbb
  speed: 1, // Rounds per second
  trail: 60, // Afterglow percentage
  shadow: false, // Whether to render a shadow
  hwaccel: false, // Whether to use hardware acceleration
  className: 'spinner', // The CSS class to assign to the spinner
  zIndex: 2e9, // The z-index (defaults to 2000000000)
  top: 'auto', // Top position relative to parent in px
  left: 'auto' // Left position relative to parent in px
};

$(".control-label").hide();

if (<%= @brand.captcha %> == true){
 var url = '/brands/getCaptcha'; // the script where you handle the form input.
    $('#imgHolder').html("Loading Captcha Image")
    var target = document.getElementById('imgHolder');
    var spinner = new Spinner(opts).spin(target);
    $('#submitButtonId').hide();
    $.ajax({
           type: "POST",
           url: url,
           data: {
              "brandProductId":"<%= @brand.retailer_id %>"
            },
           dataType: "json",
           //contentType:"application/json",
           success: function(data)
           {  
              spinner.stop();
              $('#submitButtonId').show();
              var data = jQuery.parseJSON(data);
               $('#imgHolder').replaceWith("<img id=\"captchaUrl\"\/>");
               $('#captchaUrl').attr("src",'http:'+data.captchaUrl);
               $('#captchaLine').show();
               console.log(data ); // show response from the php script.
               $("#submitButtonId").click(function() {
              var captchaId = data.captchaId;
              var url = "/brands/getBalance"; // the script where you handle the form input.
              var target = document.getElementById('submitButtonId');
              $('#submitButtonId').button('loading')

              var spinner = new Spinner(opts).spin(target);
              $.ajax({
                     type: "POST",
                     url: url,
                     data: {
                          "cardNumber":$('input#cardNumber').val(),
                          "pin":$('input#pin').val(),
                          "brandProductId":"<%= @brand.retailer_id %>",
                          "captchaId":captchaId,
                          "captchaInput":$('input#captchaText').val()

                     },
                     dataType: "json",
                     success: function(data)
                     {
                         spinner.stop();
                         $('#submitButtonId').button('reset')
                         var data = jQuery.parseJSON(data);
                         $('#captchaUrl').replaceWith("<div id=\"holder\"></div>");
                         
                         if (data._ERROR_MESSAGE_){
                            $('#holder').addClass('alert alert-error');
                            $('#holder').html(data._ERROR_MESSAGE_);
                         } else {
                            $('#holder').addClass('alert alert-success');
                            $('#holder').html(data.cardBalance);
                         }

                         console.log(data); // show response from the php script.
                     }
                   });

              return false; // avoid to execute the actual submit of the form.
              });
           }
         });
  }
  else{
        $('#holder').html("Not a Captcha brand")
        // this is the id of the submit button
        $("#submitButtonId").click(function() {
             var target = document.getElementById('submitButtonId');
             $('#submitButtonId').button('loading')

             var spinner = new Spinner(opts).spin(target);
//            $('#submitButtonId').button('loading')
            var url = "/brands/getBalance"; // the script where you handle the form input.

            $.ajax({
                   type: "POST",
                   url: url,
                   data: {
                        "cardNumber":$('input#cardNumber').val(),
                        "pin":$('input#pin').val(),
                        "brandProductId":"<%= @brand.retailer_id %>"

                   },
                   dataType: "json",
                   success: function(data)
                   {    
                       spinner.stop();
                       $('#submitButtonId').button('reset')
                       var data = jQuery.parseJSON(data);
                       $('#holder').html(data.cardBalance);

                       console.log(data); // show response from the php script.
                   }
                 });

            return false; // avoid to execute the actual submit of the form.
        });

  }
  </script>

app/views/cities/_form.html.erb
<%= form_for @city do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/cities/edit.html.erb
<% title "Edit City" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @city %> |
  <%= link_to "View All", cities_path %>
</p>

app/views/cities/index.html.erb
<% title "Cities" %>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Active</th>
  </tr>
  <% for city in @cities %>
    <tr>
      <td><%= city.name %></td>
      <td><%= city.url %></td>
      <td><%= city.active %></td>
      <td><%= link_to "Show", city %></td>
      <td><%= link_to "Edit", edit_city_path(city) %></td>
      <td><%= link_to "Destroy", city, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New City", new_city_path %></p>

app/views/cities/new.html.erb
<% title "New City" %>

<%= render 'form' %>

<p><%= link_to "Back to List", cities_path %></p>

app/views/cities/show.html.erb
<% title "City" %>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>
<p>
  <strong>Url:</strong>
  <%= @city.url %>
</p>
<p>
  <strong>Active:</strong>
  <%= @city.active %>
</p>

<p>
  <%= link_to "Edit", edit_city_path(@city) %> |
  <%= link_to "Destroy", @city, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", cities_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :brand_id %><br />
    <%= f.text_field :brand_id %>
  </p>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/posts/edit.html.erb
<% title "Edit Post" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @post %> |
  <%= link_to "View All", posts_path %>
</p>

app/views/posts/index.html.erb
<% title "Posts" %>

<table>
  <tr>
    <th>Brand</th>
    <th>Title</th>
    <th>Price</th>
    <th>Value</th>
    <th>Url</th>
  </tr>
  <% for post in @posts %>
    <tr>
      <td><%= post.brand.name %></td>
      <td><%= post.title %></td>
      <td><%= post.price %></td>
      <td><%= post.value %></td>
      <td><a href="<%= post.url %>"/>link</a></td>
      <td><%= link_to "Show", post %></td>
      <td><%= link_to "Edit", edit_post_path(post) %></td>
      <td><%= link_to "Destroy", post, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Post", new_post_path %></p>

app/views/posts/new.html.erb
<% title "New Post" %>

<%= render 'form' %>

<p><%= link_to "Back to List", posts_path %></p>

app/views/posts/show.html.erb
<% title "Post" %>

<p>
  <strong>Brand:</strong>
  <%= @post.brand_id %>
</p>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
  <strong>Price:</strong>
  <%= @post.price %>
</p>
<p>
  <strong>Value:</strong>
  <%= @post.value %>
</p>
<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<p>
  <%= link_to "Edit", edit_post_path(@post) %> |
  <%= link_to "Destroy", @post, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", posts_path %>
</p>